services:
  product:
    build: microservices/ProductService
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      productsDB:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - '8081:8081'
    networks:
      - ecommerce-net

  review:
    build: microservices/ReviewService
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      reviewsDB:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - '8082:8082'
    networks:
      - ecommerce-net

  eureka:
    build: spring-cloud/EurekaServer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    mem_limit: 512m
    networks:
      - ecommerce-net

  config-server:
    build: spring-cloud/ConfigServer
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - $PWD/config-repo:/config-repo
    networks:
      - ecommerce-net

  productsDB:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'productsdb'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d productsdb']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  reviewsDB:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'reviewsDB'
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d reviewsDB']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  customersDB:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'customersDB'
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d customersDB']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  rabbitmq:
    image: rabbitmq:4.0.7-management
    mem_limit: 512m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 2s
      retries: 60
    networks:
      - ecommerce-net

  auth-server:
    build: spring-cloud/AuthServer
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      customersDB:
        condition: service_healthy
    healthcheck:
      test:
        ['CMD', 'wget', '-O -', '-q', 'http://localhost:9999/actuator/health']
      interval: 5s
      timeout: 2s
      retries: 60
    networks:
      - ecommerce-net
  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
      - SERVER_SSL_BUNDLE_JKS_GATEWAY_KEYSTORE_LOCATION=file:/keystore/edge-test.p12
      - SERVER_SSL_BUNDLE_JKS_GATEWAY_KEYSTORE_PASSWORD=testtest
    volumes:
      - $PWD/keystore:/keystore
    build: spring-cloud/Gateway
    mem_limit: 512m
    ports:
      - '8443:8443'
    depends_on:
      auth-server:
        condition: service_healthy
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
